input {
  beats {
    port => 5044
  }
}

filter {
  if [log][level] == "error" {
    mutate { add_tag => ["critical"] }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "winlogbeat-%{+YYYY.MM.dd}"
  }
} 
